# Site
name: '800Lans Gallery'
description: '800Lans Gallery is where we celebrate local artist'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/800LansGallery'
disqus: 'demowebsite'
email: '800lans@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jordon:
      name:           Jordon
      site:           https://www.wowthemes.net
      avatar:         /assets/images/blackguyicon.png
      bio:            "Hi, I am Jordon, The creator of this gallery, I hope you enjoy it!"
      email:          jordonmurray266@gmail.com
      twitter:        https://twitter.com/wowthemesnett

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jordon
      avatar: /assets/images/blackguyicon.png 
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]